#!/bin/bash
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin:$GOBIN
cd /root
echo "let g:pathogen_disabled = [$DISABLE]" > .vimrc
echo "execute pathogen#infect('/ext/bundle/{}')" >> .vimrc
mkdir -p /root/.vim_runtime/temp_dirs
cat .vimrc~ >> .vimrc
echo "source /ext/.vimrc" >> .vimrc
cd /root/workspace/
vim $@
